
- name: "Debug print"
  debug:
    msg: "mvn clean install -f {{ localD3S_rootPath }}/D3S.pom"

- name: "Run maven"
  command: "mvn clean install -f {{ localD3S_rootPath }}/D3S.pom"
  register: maven_debug

#
- name: "Maven print"
  debug:
    var: maven_debug.stdout

- name: "Create a zip for performance reasons"
  archive:
    path: "{{ localD3S_distPath }}/lib/"
    dest: "{{ localD3S_distPath }}/libs.tgz"
